
const data =[
    {
    id: 0,
    metarial: "Python",
    numLecture: "القائمة كلها",
    size: 800,
    doctor: "نور حمص",
    date: "2021-10-18",
    link: 'https://www.youtube.com/watch?v=nyz2sieUtsI',
    category:"Programming",
  },
  {
    id: 1,
    metarial: "Algorithms",
    numLecture: "الاولى",
    size: 80,
    doctor: "محمد سعيد",
    date: "2021-11-18",
    link: 'https://www.youtube.com/watch?v=Oj8LAsuGo5k&list=PL9fwy3NUQKwZehIm7RGZM5M1SWdayxKRo',
    category:"Algorithms",
  },
  {
    id: 2,
    metarial: "Algorithms",
    numLecture: "التانية",
    size: 98,
    doctor: "محمد سعيد",
    date: "2021-11-22",
    link: 'https://www.youtube.com/watch?v=fnLeWlOSU78&list=PL9fwy3NUQKwZehIm7RGZM5M1SWdayxKRo&index=2',
    category:"Algorithms",
  },
  {
    id: 3,
    metarial: "Algorithms",
    numLecture: "التالثة",
    size: 95,
    doctor: "محمد سعيد",
    date: "2021-11-25",
    link: 'https://www.youtube.com/watch?v=cBlGSDX7byg&list=PL9fwy3NUQKwZehIm7RGZM5M1SWdayxKRo&index=3',
    category:"Algorithms",
  },
  {
    id: 4,
    metarial: "Data structure",
    numLecture: "الاولى",
    size: 155,
    doctor: "عادل نسيم",
    date: "2022-1-20",
    link: 'https://www.youtube.com/watch?v=owCqVRbZlbg&list=PLCInYL3l2AajqOUW_2SwjWeMwf4vL4RSp',
    category:"Data structure",
  },
  {
    id: 5,
    metarial: "Data structure",
    numLecture: "التانية",
    size: 110,
    doctor: "عادل نسيم",
    date: "2022-1-21",
    link: 'https://www.youtube.com/watch?v=sHhVsGQz9MI&list=PLCInYL3l2AajqOUW_2SwjWeMwf4vL4RSp&index=2',
    category:"Data structure",
  },
  {
    id: 6,
    metarial: "Data structure",
    numLecture: "التالثة",
    size: 155,
    doctor: "عادل نسيم",
    date: "2022-1-27",
    link: 'https://www.youtube.com/watch?v=vdPNQzgBu_I&list=PLCInYL3l2AajqOUW_2SwjWeMwf4vL4RSp&index=3',
    category:"Data structure",
  },
  {
    id: 7,
    metarial: "Algorithms",
    numLecture: "الاولى",
    size: 135,
    doctor: "انس علي",
    date: "2022-3-6",
    link: 'https://www.youtube.com/watch?v=McifeJjrvpI',
    category:"Algorithms",
  },
  {
    id: 8,
    metarial: "Java",
    numLecture: "الاولى",
    size: 215,
    doctor: "عادل نسيم",
    date: "2020-9-20",
    link: 'https://www.youtube.com/watch?v=McifeJjrvpI',
    category:"Programming",
  },
  {
    id: 9,
    metarial: "Java",
    numLecture: "التانية",
    size: 105,
    doctor: "عادل نسيم",
    date: "2020-9-24",
    link: 'https://www.youtube.com/watch?v=wJKgqYj4mtU&list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN&index=2',
    category:"Programming",
  },
  {
    id: 10,
    metarial: "Java",
    numLecture: "التالثة",
    size: 150,
    doctor: "عادل نسيم",
    date: "2020-9-28",
    link: 'https://www.youtube.com/watch?v=vtHwpyk5v08&list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN&index=3',
    category:"Programming",
  },
  {
    id: 11,
    metarial: "Java",
    numLecture: "باقي المحاضرات",
    size: 0,
    doctor: "عادل نسيم",
    date: "2020-9-28",
    link: 'https://www.youtube.com/playlist?list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN',
    category:"Programming",
  },

]

export default data;