
const data =[
  {
    id: 0,
    metarial: "Html",
    numLecture: "( Hayper Text Markup Language )",
    size: "كورس أساسيات html",
    doctor: "اسامة الزيرو",
    date: "24",
    link: 'https://www.youtube.com/watch?v=6QAELgirvjs&list=PLDoPjvoNmBAw_t_XWUFbBX-c9MafPk9ji',
    category:"Frontend web",
},
{
  id: 1,
  metarial: "Css",
  numLecture: "( Cascading Style Sheets )",
  size: "كورس أساسيات Css",
  doctor: "اسامة الزيرو",
  date: "88",
  link: 'https://www.youtube.com/watch?v=X1ulCwyhCVM&list=PLDoPjvoNmBAzjsz06gkzlSrlev53MGIKe',
  category:"Frontend web",
},
{
  id: 2,
  metarial: "Js",
  numLecture: "( Java Script )",
  size: "BootCamp",
  doctor: "اسامة الزيرو",
  date: "188",
  link: 'https://www.youtube.com/watch?v=GM6dQBmc-Xg&list=PLDoPjvoNmBAx3kiplQR_oeDqLDBUDYwVv',
  category:"Frontend web",
},
{
  id: 3,
  metarial: "تطبيقات عملية على Html & Css",
  numLecture: "",
  size: '',
  doctor: "اسامة الزيرو",
  date: "22",
  link: 'https://www.youtube.com/watch?v=lXVP3rDH9EU&list=PLDoPjvoNmBAxuCSp2_-9LurPqRVwketnc',
  category:"Frontend web",
},
{
  id: 4,
  metarial: "Clone Youtube",
  numLecture: "By Html & Css",
  size: '',
  doctor: "اسلام",
  date: "1",
  link: 'https://www.youtube.com/watch?v=Hnm3BP-tjD8&t=2691s',
  category:"Frontend web",
},
{
  id: 5,
  metarial: "Js تطبيقات عملية",
  numLecture: "القائمة كلها",
  size: '',
  doctor: "اسامة الزيرو",
  date: "2021-10-18",
  link: 'https://www.youtube.com/watch?v=Auo9jbFJf74&list=PLDoPjvoNmBAxhsMvDrXldKClH7FdE8WSf',
  category:"Frontend web",
},
{
  id: 6,
  metarial: "Data structure",
  numLecture: "التالثة",
  size: 155,
  doctor: "عادل نسيم",
  date: "2022-1-27",
  link: 'https://www.youtube.com/watch?v=vdPNQzgBu_I&list=PLCInYL3l2AajqOUW_2SwjWeMwf4vL4RSp&index=3',
  category:"Backend web",
},
{
  id: 7,
  metarial: "Algorithms",
  numLecture: "الاولى",
  size: 135,
  doctor: "انس علي",
  date: "2022-3-6",
  link: 'https://www.youtube.com/watch?v=McifeJjrvpI',
  category:"Backend web",
},
{
  id: 8,
  metarial: "Java",
  numLecture: "الاولى",
  size: 215,
  doctor: "عادل نسيم",
  date: "2020-9-20",
  link: 'https://www.youtube.com/watch?v=McifeJjrvpI',
  category:"Android",
},
{
  id: 9,
  metarial: "Java",
  numLecture: "التانية",
  size: 105,
  doctor: "عادل نسيم",
  date: "2020-9-24",
  link: 'https://www.youtube.com/watch?v=wJKgqYj4mtU&list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN&index=2',
  category:"Android",
},
{
  id: 10,
  metarial: "Java",
  numLecture: "التالثة",
  size: 150,
  doctor: "عادل نسيم",
  date: "2020-9-28",
  link: 'https://www.youtube.com/watch?v=vtHwpyk5v08&list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN&index=3',
  category:"Android",
},
{
  id: 11,
  metarial: "Android Studio",
  numLecture: "باقي المحاضرات",
  size: 0,
  doctor: "عادل نسيم",
  date: "2020-9-28",
  link: 'https://www.youtube.com/playlist?list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN',
  category:"Android",
},
{
  id: 12,
  metarial: "PHP",
  numLecture: "باقي المحاضرات",
  size: 0,
  doctor: "عادل نسيم",
  date: "2020-9-28",
  link: 'https://www.youtube.com/playlist?list=PLCInYL3l2AajYlZGzU_LVrHdoouf8W6ZN',
  category:"Backend web",
},

]

export default data;